# Esta linha abaixo é OBRIGATÓRIA para o Flutter reconhecer os comandos
path_to_utils = File.expand_path(File.join('..', 'Flutter', 'podhelper.rb'), __FILE__)
load path_to_utils

platform :ios, '12.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Agora o comando vai funcionar porque demos o "load" acima
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Força todos os Pods a compilarem para iOS 12
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
    end
  end
end
